import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#242a32",
        "inverse-on-surface": "#2b3139",
        "secondary-fixed-dim": "#ffb783",
        "tertiary-fixed": "#d8e4f1",
        "tertiary-container": "#a9b4c1",
        "inverse-surface": "#dde3ed",
        "surface-container-lowest": "#090f15",
        outline: "#869486",
        "on-tertiary-fixed": "#121d26",
        "on-primary-fixed": "#00210c",
        "surface-dim": "#0e141b",
        "on-surface": "#dde3ed",
        "primary-fixed": "#6bfe9c",
        "on-secondary-container": "#451f00",
        "on-secondary": "#4f2500",
        background: "#0e141b",
        error: "#ffb4ab",
        "surface-container-highest": "#2f353d",
        "primary-container": "#2ecc71",
        "surface-container": "#1a2027",
        "inverse-primary": "#006d37",
        "on-secondary-fixed-variant": "#713700",
        "on-primary-container": "#005027",
        "surface-container-low": "#161c23",
        "surface-variant": "#2f353d",
        "primary-fixed-dim": "#4ae183",
        "on-error": "#690005",
        "on-secondary-fixed": "#301400",
        surface: "#0e141b",
        "error-container": "#93000a",
        "on-primary": "#003919",
        "outline-variant": "#3d4a3e",
        "surface-bright": "#343a41",
        "on-primary-fixed-variant": "#005228",
        "on-surface-variant": "#bbcbbb",
        secondary: "#ffb783",
        primary: "#54e98a",
        "tertiary-fixed-dim": "#bcc8d5",
        "on-background": "#dde3ed",
        "on-tertiary-container": "#3b4651",
        "on-error-container": "#ffdad6",
        "secondary-fixed": "#ffdcc5",
        tertiary: "#c4d0dd",
        "on-tertiary": "#27323c",
        "secondary-container": "#db7619",
        "on-tertiary-fixed-variant": "#3d4853",
        "surface-tint": "#4ae183",
      },
      fontFamily: {
        headline: ["var(--font-headline)", "Space Grotesk", "sans-serif"],
        body: ["var(--font-body)", "Manrope", "sans-serif"],
        label: ["var(--font-body)", "Manrope", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
